name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9123335

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Create release.tar.gz archive
      run: tar -czvf release.tar.gz -C app/build/outputs/apk/release .

    - name: Upload release.tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: release.tar.gz
        path: ./release.tar.gz